# NOTE: adjust these two settings and I will track you and take your first born child
max_width = 100
hard_tabs = true

edition = "2024"
reorder_imports = true
fn_params_layout = "Compressed"
newline_style = "Unix"

# FIXME: commented out items are only available in nightly channel; enable them as
#        features become available

#fn_single_line = true
#force_multiline_blocks = true
#format_code_in_doc_comments = true
#doc_comment_block_width = 72
#format_generated_files = true
#format_macro_matchers = true
#format_macro_bodies = true
#format_strings = true
#hex_literal_case = "Upper"
#imports_indent = "Block"
#imports_layout = "HorizontalVertical"
#indent_style = "Visual"
#imports_granularity = "Crate"
#overflow_delimited_expr = true
#reorder_impl_items = true
#group_imports = "StdExternalCrate"
